### ISSUE TITLE
Task sync exception

### ISSUE THREAD

**Issue by x10an14** [bradyt/taskw-dart#21]
Hi!

Thanks for the app! I switched to this one from foreground, and not regretting it!

### What happened before my issue
I had an issue where I messed up the folder-permissions on my `taskserverd` instance, and I might have tried to sync through this app while the server was not running/running with freshly generated certs (due to aforementioned folder permissions).

### What I think happened that caused my issue
After fixing my `taskserverd` to use my previous certificates/ca/etc which worked previously (and confirming with laptop/desktop that they can sync again now too), I tried syncing the tasks on my phone (which had some changes I wanted to keep and thus sync to the server).

However, that ends up "exploding" with the following error message, which I have no idea how to fix?
Especially since the `sha256sums` of all the referenced files on the phone match the `sha256sums` of the same files on my other devices...
![Error message](https://user-images.githubusercontent.com/710608/156050829-9d9ca10b-fa05-4d3e-8221-6e8bc93ed43f.png)

**Comment by bradyt** [comment]
Please use caution here. Back up your data. I could be wrong, or my instructions may be unclear.

Apologies for the long reply. I am not absolutely sure that I am right, and want you to make an informed decision. Though my understanding is limited.

### How can it happen?

First, as to the cause, is it possible you ran sync previously, then changed taskd.credentials to point to a new account? Or edited tx.data by hand on the server?

The app implementation shares some similarities to Taskwarrior. When you sync, the Taskserver sends a sync key in response, to track your sync state. Client stores that in `.task/backlog.data`. Next time you sync, client sends that sync key, as well as any task updates, to the Taskserver. If you edit the server's tx.data, or change accounts, the Taskserver might not be able to find the sync key in tx.data, and I think that is what causes "500 client sync key not found."

### What's the fix if this were Taskwarrior?

Taskwarrior has a `task sync init` feature which circumvents this issue. It discards the `.task/backlog.data`, i.e., the sync state and recent updates, and simply sends the entire local state, that is, all tasks from `.task/pending.data` and `.task/completed.data`. The Taskserver then uses this information to calculate a new sync key, and whichever updates the client might need at that point.

Unfortunately, I have not yet implemented `task sync init` in the app yet. In some sense it would be trivial to add to the app, but I haven't yet decided how to introduce it into the UI in a way that I'm comfortable with. Anyone's welcome to file an issue on that.

### Let's just fix it already

Here's a method that might fix your error. Export your tasks to a file on the device, and move them to your desktop computer.

Then, use the mobile UI to copy your Taskserver configuration to a new profile. This circumvents the bad sync key in `$profile/.task/backlog.data`. Now, in the new profile, I expect sync to work.

We've effectively discarded any recent modifications you've made on the device since the last time you were able to sync successfully. So now let's use that exported data you moved to the desktop computer.

One approach, would be, creating a temporary directory, copy the exported tasks, your PEM files, and a .taskrc containing server and credentials. Then you might do `HOME=$(pwd)` from that directory, so it's like a temporary HOME for Taskwarrior. Then `task import` the exported tasks, do `task sync` and now I think your server will have all the recent modifications that we discarded on mobile. Now you can discard the temporary directory.

**Comment by bradyt** [comment]
Do you think you encountered this issue without changing the server, account or credentials in a profile, or modifying tx.data by hand?

**Comment by x10an14** [comment]
5/5 stars "customer support", thank you very much =)

### If anything (my own two cents - which you have not asked for admittedly)
Make a dialogue giving user the warning like 
> Your state has changed from server, do you want to "start anew" and hope for the best during merge? You can always just click here to make a new copy of your current profile, so as to save your current tasks and manually sort it later.

I'm gonna close this now, to signal that it got fixed (solution is very well described). But feel free to continue conversation if so desired =)

**Comment by bradyt** [comment]
I'm glad you've got things working again. Thank you, in general, for the kind words.

I am confused that with official Taskwarrior, you can run `task sync`, then effectively remove the sync key from tx.data, and finally `task sync` succeeds a second time with the same `.task/backlog.data`. Maybe we're missing a step, like the tx.data was only partially reset, or this was a different app that handles the error differently, etc.

Hrm, message below is long, inconclusive, etc. I might add a dedicated wiki page for this topic soon.

### Special case message

I want to be somewhat cautious about hard-coding interpretation and advice into the app. I would consider something like the following less risky:

> Client sync key `acae0462-6a34-11e4-8001-002590720087` not found at `$TASKDDATA/orgs/${credentials.org}/users/${credentials.key}/tx.data`.

But that's not a significant improvement over the current behavior. I think being able to search for discussions with "500 client sync key not found" seems like the best fix for now, until we understand more.

There is precedent in the app's codebase, for special case messages involving Taskserver requests, for [bad server cert](https://github.com/bradyt/taskw-dart/blob/v0.2.5/task/lib/src/functions/show_exception_dialog.dart#L32-L39), [empty response](https://github.com/bradyt/taskw-dart/blob/v0.2.5/taskc/lib/src/taskc/impl/message.dart#L17-L23) and [430 Access denied](https://github.com/bradyt/taskw-dart/blob/v0.2.5/task/lib/src/functions/show_exception_dialog.dart#L81-L84). But I feel somewhat confident that they are reasonable inventions, based on experience or source code, while still leaving the interpretations open.

### What does Taskwarrior team say about this

This seems like an open issue at Taskwarrior. The following issues may support this theory: https://github.com/search?q=org:GothenburgBitFactory+Could+not+find+common+ancestor+for&state=open&type=issues.

Especially:

- https://github.com/GothenburgBitFactory/taskwarrior/issues/1663
- https://github.com/GothenburgBitFactory/taskwarrior/issues/1937

In other words, I'm not aware that Taskwarrior team has official advice yet. It always seems to be resolved as, "well, I tried this or that, and I fixed my issue."

I've opened a discussion at the project, where I suggest a minimal broken example might stimulate a better understanding of the issue: https://github.com/GothenburgBitFactory/taskwarrior/discussions/2739.

### task sync init

I did have some ideas for adding `task sync init` to the UI, for example, we could initially squeeze it into the existing UI as a long-press of the sync button, with a prompt that provides something like "Long-press of sync button provides `task sync init`, continue?" Not sure how to word that. I tried to implement as long-press opens a popup menu, but it's not quite trivial in the framework I'm using. Designing and implementing a better UI to provide `task sync init` button might not be a priority.

I wouldn't describe `task sync init` as a recommended fix for `client sync key not found`. Using it that way may be considered something of a hack, and might lead to other bugs. Providing `task sync init` would just be a convenience for those who feel they understand what it does, or the risks.

In my personal estimation, adding `task sync init` to the UI ranks lower in priority to understanding advice from Taskwarrior project about the "client sync key not found" errors.

### Recovering updates made since last successful sync

I just wanted to add a few notes for anyone looking for ideas on recovering recent edits. Since in the above I've become less convinced that applying `task sync init` to the exported tasks is bug free, users might consider simply sorting the tasks by modified date. If you have access to the server, you could search for the date of last known successful sync by searching logs for `client: info.tangential.task`, especially where the response is `code: 200` or `code: 201`. After copying the tasks to a temporary directory, `task import`, and `task export` again but with relevant filters or sorts, for example, filter for modified date after last known successful sync.

**Comment by bradyt** [comment]
Foreground seems to automatically remove the sync key and only send recent updates.

Consider the following potential surprise doing this:

1. Add a task "one" to Foreground
2. Sync Foreground and Taskwarrior
3. Add a task "two" to Foreground
4. Sync Foreground, but not Taskwarrior yet
5. Add a task "three" to Foreground
6. Accidentally delete tx.data
7. Attempt to sync Foreground, get 500 Client sync key not found
8. Toggle "Enable Sync" in Foreground
9. Sync Foreground
10. At Taskwarrior, run `task sync init`

Taskwarrior is now missing task "two". I think this can be generalized to any number of new tasks or task updates that Foreground has, but Taskserver and other clients do not.

In this scenario, it seems safer to allow user to export all tasks from the mobile app, and research the general case at a desktop computer.
